/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mugui_jni_Tool_DJni */

#ifndef _Included_com_mugui_jni_Tool_DJni
#define _Included_com_mugui_jni_Tool_DJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mugui_jni_Tool_DJni
 * Method:    Init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mugui_jni_Tool_DJni_Init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mugui_jni_Tool_DJni
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mugui_jni_Tool_DJni_quit
  (JNIEnv *, jobject);

/*
 * Class:     com_mugui_jni_Tool_DJni
 * Method:    getWinRect
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_mugui_jni_Tool_DJni_getWinRect
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mugui_jni_Tool_DJni
 * Method:    getWinAppHandleByID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mugui_jni_Tool_DJni_getWinAppHandleByID
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mugui_jni_Tool_DJni
 * Method:    getWinAppIDByName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mugui_jni_Tool_DJni_getWinAppIDByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mugui_jni_Tool_DJni
 * Method:    getWinAppFilePath
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mugui_jni_Tool_DJni_getWinAppFilePath
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
