/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mugui_ui_mainUI */

#ifndef _Included_com_mugui_ui_mainUI
#define _Included_com_mugui_ui_mainUI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mugui_ui_mainUI_FOCUS_TRAVERSABLE_UNKNOWN
#define com_mugui_ui_mainUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef com_mugui_ui_mainUI_FOCUS_TRAVERSABLE_DEFAULT
#define com_mugui_ui_mainUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef com_mugui_ui_mainUI_FOCUS_TRAVERSABLE_SET
#define com_mugui_ui_mainUI_FOCUS_TRAVERSABLE_SET 2L
#undef com_mugui_ui_mainUI_TOP_ALIGNMENT
#define com_mugui_ui_mainUI_TOP_ALIGNMENT 0.0f
#undef com_mugui_ui_mainUI_CENTER_ALIGNMENT
#define com_mugui_ui_mainUI_CENTER_ALIGNMENT 0.5f
#undef com_mugui_ui_mainUI_BOTTOM_ALIGNMENT
#define com_mugui_ui_mainUI_BOTTOM_ALIGNMENT 1.0f
#undef com_mugui_ui_mainUI_LEFT_ALIGNMENT
#define com_mugui_ui_mainUI_LEFT_ALIGNMENT 0.0f
#undef com_mugui_ui_mainUI_RIGHT_ALIGNMENT
#define com_mugui_ui_mainUI_RIGHT_ALIGNMENT 1.0f
#undef com_mugui_ui_mainUI_serialVersionUID
#define com_mugui_ui_mainUI_serialVersionUID -7644114512714619750i64
#undef com_mugui_ui_mainUI_serialVersionUID
#define com_mugui_ui_mainUI_serialVersionUID 4613797578919906343i64
#undef com_mugui_ui_mainUI_INCLUDE_SELF
#define com_mugui_ui_mainUI_INCLUDE_SELF 1L
#undef com_mugui_ui_mainUI_SEARCH_HEAVYWEIGHTS
#define com_mugui_ui_mainUI_SEARCH_HEAVYWEIGHTS 1L
#undef com_mugui_ui_mainUI_OPENED
#define com_mugui_ui_mainUI_OPENED 1L
#undef com_mugui_ui_mainUI_serialVersionUID
#define com_mugui_ui_mainUI_serialVersionUID 4497834738069338734i64
#undef com_mugui_ui_mainUI_DEFAULT_CURSOR
#define com_mugui_ui_mainUI_DEFAULT_CURSOR 0L
#undef com_mugui_ui_mainUI_CROSSHAIR_CURSOR
#define com_mugui_ui_mainUI_CROSSHAIR_CURSOR 1L
#undef com_mugui_ui_mainUI_TEXT_CURSOR
#define com_mugui_ui_mainUI_TEXT_CURSOR 2L
#undef com_mugui_ui_mainUI_WAIT_CURSOR
#define com_mugui_ui_mainUI_WAIT_CURSOR 3L
#undef com_mugui_ui_mainUI_SW_RESIZE_CURSOR
#define com_mugui_ui_mainUI_SW_RESIZE_CURSOR 4L
#undef com_mugui_ui_mainUI_SE_RESIZE_CURSOR
#define com_mugui_ui_mainUI_SE_RESIZE_CURSOR 5L
#undef com_mugui_ui_mainUI_NW_RESIZE_CURSOR
#define com_mugui_ui_mainUI_NW_RESIZE_CURSOR 6L
#undef com_mugui_ui_mainUI_NE_RESIZE_CURSOR
#define com_mugui_ui_mainUI_NE_RESIZE_CURSOR 7L
#undef com_mugui_ui_mainUI_N_RESIZE_CURSOR
#define com_mugui_ui_mainUI_N_RESIZE_CURSOR 8L
#undef com_mugui_ui_mainUI_S_RESIZE_CURSOR
#define com_mugui_ui_mainUI_S_RESIZE_CURSOR 9L
#undef com_mugui_ui_mainUI_W_RESIZE_CURSOR
#define com_mugui_ui_mainUI_W_RESIZE_CURSOR 10L
#undef com_mugui_ui_mainUI_E_RESIZE_CURSOR
#define com_mugui_ui_mainUI_E_RESIZE_CURSOR 11L
#undef com_mugui_ui_mainUI_HAND_CURSOR
#define com_mugui_ui_mainUI_HAND_CURSOR 12L
#undef com_mugui_ui_mainUI_MOVE_CURSOR
#define com_mugui_ui_mainUI_MOVE_CURSOR 13L
#undef com_mugui_ui_mainUI_NORMAL
#define com_mugui_ui_mainUI_NORMAL 0L
#undef com_mugui_ui_mainUI_ICONIFIED
#define com_mugui_ui_mainUI_ICONIFIED 1L
#undef com_mugui_ui_mainUI_MAXIMIZED_HORIZ
#define com_mugui_ui_mainUI_MAXIMIZED_HORIZ 2L
#undef com_mugui_ui_mainUI_MAXIMIZED_VERT
#define com_mugui_ui_mainUI_MAXIMIZED_VERT 4L
#undef com_mugui_ui_mainUI_MAXIMIZED_BOTH
#define com_mugui_ui_mainUI_MAXIMIZED_BOTH 6L
#undef com_mugui_ui_mainUI_serialVersionUID
#define com_mugui_ui_mainUI_serialVersionUID 2673458971256075116i64
#undef com_mugui_ui_mainUI_EXIT_ON_CLOSE
#define com_mugui_ui_mainUI_EXIT_ON_CLOSE 3L
#undef com_mugui_ui_mainUI_serialVersionUID
#define com_mugui_ui_mainUI_serialVersionUID 4827923168894442407i64
#undef com_mugui_ui_mainUI_serialVersionUID
#define com_mugui_ui_mainUI_serialVersionUID -8316019247919644043i64
#ifdef __cplusplus
}
#endif
#endif
